import 'dotenv/config';
import mongoose from 'mongoose';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { connectToDatabase } from '../server/db';
import { getAboutContent } from '../server/about-content-service';
import { getContactContent } from '../server/contact-content-service';
import { getCraftsmanshipContent } from '../server/craftsmanship-content-service';
import { getGalleryContent } from '../server/gallery-content-service';
import { getHeroContent } from '../server/hero-content-service';
import { getJournalContent } from '../server/journal-content-service';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const snapshotFilePath = path.resolve(__dirname, '..', 'server', 'seed-content-snapshot.ts');

function serializeAsSource(value: unknown) {
  return JSON.stringify(value, null, 2).replace(/</g, '\\u003c');
}

async function run() {
  await connectToDatabase();

  const [heroContent, aboutContent, galleryContent, journalContent, contactContent, craftsmanshipContent] =
    await Promise.all([
      getHeroContent(),
      getAboutContent(),
      getGalleryContent(),
      getJournalContent(),
      getContactContent(),
      getCraftsmanshipContent(),
    ]);

  const source = `import type { AboutContent } from '../src/app/lib/aboutContent';
import type { ContactContent } from '../src/app/lib/contactContent';
import type { CraftsmanshipContent } from '../src/app/lib/craftsmanshipContent';
import type { GalleryContent } from '../src/app/lib/gallery';
import type { HeroContent } from '../src/app/lib/heroContent';
import type { JournalContent } from '../src/app/lib/journal';

export type SeedContentSnapshot = {
  heroContent: HeroContent;
  aboutContent: AboutContent;
  galleryContent: GalleryContent;
  journalContent: JournalContent;
  contactContent: ContactContent;
  craftsmanshipContent: CraftsmanshipContent;
};

// Generated by scripts/refresh-seed-content.ts
export const seedContentSnapshot: SeedContentSnapshot | null = {
  heroContent: ${serializeAsSource(heroContent)} as HeroContent,
  aboutContent: ${serializeAsSource(aboutContent)} as AboutContent,
  galleryContent: ${serializeAsSource(galleryContent)} as GalleryContent,
  journalContent: ${serializeAsSource(journalContent)} as JournalContent,
  contactContent: ${serializeAsSource(contactContent)} as ContactContent,
  craftsmanshipContent: ${serializeAsSource(craftsmanshipContent)} as CraftsmanshipContent
};
`;

  await writeFile(snapshotFilePath, source, 'utf8');

  console.log(`Seed content snapshot updated at ${snapshotFilePath}`);
}

run()
  .catch((error) => {
    console.error('Failed to refresh seed content snapshot:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });
